### ISSUE TITLE
UPLOADER: detecting file changes in Windows

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRAVEPlugin#120]
Uploader is detecting file changes. These may or may not be real due to project layers being loaded in QGIS map. The vbet.log and the raster file were not loaded when I was using the uploader.

[RiverscapesViewer-Upload.log](https://github.com/Riverscapes/QRAVEPlugin/files/15119190/RiverscapesViewer-Upload.log)

[Project Link](https://data.riverscapes.net/p/4329de51-2bc7-46a6-8587-04256ecfe8e3/)

**Comment by MattReimer** [comment]
Ok. this is confirmed that the ETAG Calculator is failing on multi-part uploads. Need to get back to an etag calculator that works the same way the one on the API works.

**Comment by MattReimer** [comment]
Ok. I have fixed the issue with the MD5 calculation. This will need to be fixed in the node version of the CLI too btw but that's already tracked:

- https://github.com/Riverscapes/rs-web-monorepo/issues/63

Also this uncovered another problem where opening files changes them. That is being tracked here (so we can close this issue).

- https://github.com/Riverscapes/QRAVEPlugin/issues/121
