### ISSUE TITLE
Some Unexpected Updates...

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRAVEPlugin#18]
Hey @MattReimer I don't know if this whole 10 minute video is worth watching, but thought I would put this up here in case you are unaware of some of this.
[![](http://img.youtube.com/vi/3c2Mpq7240M/0.jpg)](http://www.youtube.com/watch?v=3c2Mpq7240M "")

- I am running QGIS version 3.12.1-București
- I started out video with old version of QRAVE installed: 0.2 (see [here](https://youtu.be/3c2Mpq7240M?t=180))
- You will see I have a [little problem upgrading to 0.4 ](https://youtu.be/3c2Mpq7240M?t=190) but can push past it by [uninstalling and reinstalling](https://youtu.be/3c2Mpq7240M?t=195).
- I end up closing Q, and opening a riverscapes project again.
- I get some warning messages, but they are all because I used an old project.
- I try to add the updated layers (e.g. slope) and it [doesn't come in correctly](https://youtu.be/3c2Mpq7240M?t=285)... i.e. the slope.qml file is not being found
- I then try to "Update Resources", which I would not expect to have to do after a new install, and then I finally get it to work.

Anyhow, the above may all be fine, but thought I would show you what one idiot user (me) is experiencing.

**Comment by MattReimer** [comment]
Hey @joewheaton all of that is good feedback. Some of that might be solved when we flip this plugin's experimental switch off. 

The upgrade problems are worrying but also very hard to test. I'll keep an eye on that for sure and put some time aside to test upgrade workflows.

When you upgrade the plugin it might not go look for the new qml files immediately because there's no hook for plugin updating so it would just come in with whatever qml files were there when the latest version shipped. This might not be overcommable and I'll need to think up another solution.

Hey future @MattReimer , you need to split this ticket into individual issues for everything actionable in that video.

**Comment by joewheaton** [comment]
Thanks @MattReimer... all makes sense. Just wanted to make sure you were aware in case it comes up for users and we know what to tell them, or if we need to make a few notes in "install" and "update" instructions.

**Comment by MattReimer** [comment]
I think we've captured all these issues in separate bugs. I'm closing this for now @joewheaton re-open if I've missed anything

#19 #15 #20
